name: mno_opds
description: Contains OPDS1 and OPDS2 parsers using OPDS classes provided by mno_shared.
version: 0.1.2
homepage: https://github.com/Mantano/mno_opds_dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dartx: ^1.2.0
  dfunc: ^0.9.0
  fimber: ^0.7.0
  http: ^1.1.0
  universal_io: ^2.0.4
  xml: ^6.4.2
  mno_commons: 
    git: 
      url: https://github.com/getBoolean/mno_commons_dart
      ref: upgrade_deps
  mno_shared:
    git: 
      url: https://github.com/getBoolean/mno_shared_dart
      ref: upgrade_deps

dev_dependencies:
  lints: ^2.1.1
  test: ^1.17.12
